// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROAMyzYH-qzIEfsvUtYETdFTHVRTM6pg',
    appId: '1:530904328350:web:82e225e7624c2426bdb38f',
    messagingSenderId: '530904328350',
    projectId: 'flash-chat-4e484',
    authDomain: 'flash-chat-4e484.firebaseapp.com',
    storageBucket: 'flash-chat-4e484.firebasestorage.app',
    measurementId: 'G-DCLGZYV4CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_KJCJWLo6sdgDhuEYhrpgcAqeJI-wLbw',
    appId: '1:530904328350:android:8e62ad77e35fb3cebdb38f',
    messagingSenderId: '530904328350',
    projectId: 'flash-chat-4e484',
    storageBucket: 'flash-chat-4e484.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkbJX5I3cqDNZCv2SAFKvDU0pvgPQAk0Q',
    appId: '1:530904328350:ios:5386c4f4b4618496bdb38f',
    messagingSenderId: '530904328350',
    projectId: 'flash-chat-4e484',
    storageBucket: 'flash-chat-4e484.firebasestorage.app',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkbJX5I3cqDNZCv2SAFKvDU0pvgPQAk0Q',
    appId: '1:530904328350:ios:5386c4f4b4618496bdb38f',
    messagingSenderId: '530904328350',
    projectId: 'flash-chat-4e484',
    storageBucket: 'flash-chat-4e484.firebasestorage.app',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDROAMyzYH-qzIEfsvUtYETdFTHVRTM6pg',
    appId: '1:530904328350:web:4ba6d68ecee0da40bdb38f',
    messagingSenderId: '530904328350',
    projectId: 'flash-chat-4e484',
    authDomain: 'flash-chat-4e484.firebaseapp.com',
    storageBucket: 'flash-chat-4e484.firebasestorage.app',
    measurementId: 'G-GKFC21B0KE',
  );
}